# Generated by Django 5.2.5 on 2025-09-10 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('speed', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(help_text='Chi phí/quãng đường giữa 2 điểm')),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_end', to='main.node')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_start', to='main.node')),
            ],
        ),
    ]
